// Top Czech locations for autocomplete: 14 regions + ~230 cities
// Sorted alphabetically.
export const CZ_LOCATIONS: string[] = [
  // Regions (kraje)
  'Hlavní město Praha',
  'Jihočeský kraj',
  'Jihomoravský kraj',
  'Karlovarský kraj',
  'Královéhradecký kraj',
  'Liberecký kraj',
  'Moravskoslezský kraj',
  'Olomoucký kraj',
  'Pardubický kraj',
  'Plzeňský kraj',
  'Středočeský kraj',
  'Ústecký kraj',
  'Vysočina',
  'Zlínský kraj',
  // Cities
  'Adamov', 'Aš',
  'Bechyně', 'Benátky nad Jizerou', 'Benešov', 'Beroun', 'Bílina', 'Bílovec', 'Blansko', 'Bohumín',
  'Boskovice', 'Brandýs nad Labem-Stará Boleslav', 'Brno', 'Bruntál', 'Břeclav', 'Bystřice nad Pernštejnem',
  'Čáslav', 'Čelákovice', 'Černošice', 'Česká Kamenice', 'Česká Lípa', 'Česká Třebová', 'České Budějovice',
  'Český Brod', 'Český Krumlov', 'Český Těšín', 'Chodov', 'Chomutov', 'Chrudim', 'Cheb',
  'Dačice', 'Děčín', 'Dobříš', 'Dobruška', 'Domažlice', 'Dubňany', 'Dvůr Králové nad Labem',
  'Frenštát pod Radhoštěm', 'Frýdek-Místek', 'Frýdlant', 'Frýdlant nad Ostravicí',
  'Havířov', 'Havlíčkův Brod', 'Hlinsko', 'Hluboká nad Vltavou', 'Hodonín', 'Holešov', 'Holice',
  'Horažďovice', 'Horní Slavkov', 'Hořice', 'Hořovice', 'Hostivice', 'Hrádek nad Nisou', 'Hradec Králové',
  'Humpolec', 'Hustopeče',
  'Jablonec nad Nisou', 'Jablonné nad Orlicí', 'Jáchymov', 'Jaroměř', 'Jeseník', 'Jičín', 'Jihlava',
  'Jilemnice', 'Jindřichův Hradec', 'Jirkov',
  'Kadaň', 'Karlovy Vary', 'Karolinka', 'Karviná', 'Kaznějov', 'Kladno', 'Klášterec nad Ohří',
  'Klatovy', 'Kolín', 'Kopřivnice', 'Kostelec nad Orlicí', 'Kralupy nad Vltavou', 'Kraslice', 'Krnov',
  'Kroměříž', 'Krupka', 'Kuřim', 'Kutná Hora', 'Kyjov',
  'Lanškroun', 'Lázně Bohdaneč', 'Lázně Bělohrad', 'Lednice', 'Letohrad', 'Libochovice', 'Liberec',
  'Lipník nad Bečvou', 'Litoměřice', 'Litomyšl', 'Litovel', 'Litvínov', 'Louny', 'Lovosice', 'Luhačovice',
  'Lysá nad Labem',
  'Mariánské Lázně', 'Mělník', 'Mikulov', 'Milevsko', 'Mladá Boleslav', 'Mnichovo Hradiště',
  'Mohelnice', 'Moravská Třebová', 'Moravské Budějovice', 'Moravský Krumlov', 'Most',
  'Náchod', 'Nejdek', 'Neratovice', 'Nová Paka', 'Nové Město na Moravě', 'Nové Město nad Metují',
  'Nový Bor', 'Nový Bydžov', 'Nový Jičín', 'Nymburk', 'Nýrsko',
  'Odry', 'Olomouc', 'Opava', 'Orlová', 'Ostrava', 'Ostrov', 'Otrokovice',
  'Pacov', 'Pardubice', 'Pelhřimov', 'Písek', 'Planá', 'Plzeň', 'Poděbrady', 'Polička', 'Polná',
  'Přelouč', 'Přerov', 'Přeštice', 'Příbor', 'Příbram', 'Prachatice', 'Praha', 'Prostějov',
  'Rakovník', 'Rokycany', 'Rosice', 'Roudnice nad Labem', 'Rožnov pod Radhoštěm', 'Rumburk',
  'Rychnov nad Kněžnou', 'Rýmařov',
  'Sázava', 'Sedlčany', 'Semily', 'Slaný', 'Slavkov u Brna', 'Slušovice', 'Smiřice', 'Sokolov',
  'Sobotka', 'Soběslav', 'Stochov', 'Strakonice', 'Strážnice', 'Stříbro', 'Studénka', 'Sušice',
  'Svitavy',
  'Šlapanice', 'Šternberk', 'Štětí', 'Šumperk',
  'Tábor', 'Tachov', 'Telč', 'Teplice', 'Tišnov', 'Třebíč', 'Třeboň', 'Třinec', 'Trutnov',
  'Turnov', 'Týn nad Vltavou', 'Týnec nad Sázavou',
  'Uherský Brod', 'Uherské Hradiště', 'Ústí nad Labem', 'Ústí nad Orlicí',
  'Valašské Klobouky', 'Valašské Meziříčí', 'Varnsdorf', 'Vamberk', 'Velešín', 'Velké Meziříčí',
  'Veselí nad Lužnicí', 'Veselí nad Moravou', 'Vimperk', 'Vizovice', 'Vlašim', 'Vodňany',
  'Votice', 'Vracov', 'Vrchlabí', 'Vsetín', 'Vysoké Mýto', 'Vyškov',
  'Zábřeh', 'Zliv', 'Zlín', 'Znojmo',
  'Žamberk', 'Žatec', 'Ždár nad Sázavou', 'Železný Brod', 'Žebrák',
];
