// Slovenská sada otázek kvízu „historie značek". Vzor kviz.pl.ts.
//
// ‼️ q10, q11 a q13 NEJSOU překlad: české znění se ptá na české sazby VCS,
// na BISS v korunách a na LPIS spravovaný ÚKZÚZ/SZIF. Slovenské verze jsou
// psané ručně tak, aby netvrdily čísla, která by musela být vymyšlená.
import type { QuizQuestion } from './kviz';

export const KVIZ_HISTORIE_SK: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Ktorá značka ako prvá uviedla bezstupňovú CVT prevodovku do sériového traktora?',
    options: [
      { text: 'John Deere' },
      { text: 'Fendt' },
      { text: 'Massey Ferguson' },
      { text: 'Case IH' },
    ],
    correct: 1,
    explanation: 'Fendt uviedol Vario CVT v roku 1995 v modeli Favorit 926 Vario. Stal sa štandardom prémiových traktorov — ostatní výrobcovia pridali vlastné CVT (JD AutoPowr, NH Auto Command, Case CVX) až po roku 2000.',
    sourceUrl: '/slovnik/cvt-prevodovka/',
    sourceLabel: 'CVT prevodovka',
  },
  {
    id: 'q2',
    question: 'V ktorom roku John Deere vyrobil svoj prvý oceľový pluh?',
    options: [
      { text: '1810' },
      { text: '1837' },
      { text: '1865' },
      { text: '1900' },
    ],
    correct: 1,
    explanation: 'John Deere (kováč z Grand Detour, Illinois) skonštruoval prvý oceľový pluh v roku 1837. Tento pluh dokázal obrábať ťažkú prérijnú pôdu Stredozápadu — vďaka tomu sa Deere stal základom americkej poľnohospodárskej revolúcie.',
    sourceUrl: '/znacky/john-deere/',
    sourceLabel: 'John Deere',
  },
  {
    id: 'q3',
    question: 'Čo je AdBlue?',
    options: [
      { text: 'Modrá olejová farba na striekanie traktorov' },
      { text: 'Chladiaca kvapalina pre dieselové motory' },
      { text: '32,5% vodný roztok močoviny, ktorý znižuje emisie NOx' },
      { text: 'Aditívum proti zamŕzaniu nafty' },
    ],
    correct: 2,
    explanation: 'AdBlue je 32,5% vodný roztok močoviny (chemicky CO(NH₂)₂ + H₂O), ktorý sa vstrekne do výfuku dieselových motorov. V SCR katalyzátore reaguje s NOx → neškodný dusík a vodu. Štandard od emisnej normy Stage IV.',
    sourceUrl: '/slovnik/adblue/',
    sourceLabel: 'AdBlue',
  },
  {
    id: 'q4',
    question: 'Koľko rokov trvalo Zetoru, kým postavil prvý milión traktorov?',
    options: [
      { text: '20 rokov (1946–1966)' },
      { text: '40 rokov (1946–1986)' },
      { text: '30 rokov (1946–1976)' },
      { text: '50 rokov (1946–1996)' },
    ],
    correct: 2,
    explanation: 'Zetor vyrobil miliónty traktor v roku 1976 — 30 rokov od založenia (1946). V tom čase bol Zetor jedným z najväčších výrobcov traktorov v Európe a kľúčovým exportérom do krajín RVHP, Indie, Iraku a Etiópie.',
    sourceUrl: '/znacky/zetor/',
    sourceLabel: 'Zetor',
  },
  {
    id: 'q5',
    question: 'Ktorá značka tvrdí, že vynašla trojbodový hydraulický záves (Ferguson System)?',
    options: [
      { text: 'John Deere' },
      { text: 'Massey Ferguson (pôvodne Harry Ferguson)' },
      { text: 'Fiat' },
      { text: 'International Harvester' },
    ],
    correct: 1,
    explanation: 'Harry Ferguson (severoírsky konštruktér) patentoval Ferguson System v 30. rokoch 20. storočia — trojbodový hydraulický záves s automatickou reguláciou zaťaženia. V roku 1953 sa firma zlúčila s Massey-Harris → Massey-Ferguson. Trojbod je dodnes štandardom.',
    sourceUrl: '/slovnik/tribod/',
    sourceLabel: 'Trojbodový záves',
  },
  {
    id: 'q6',
    question: 'Aký je rozdiel medzi PTO 540 a 540E (Economy)?',
    options: [
      { text: '540E má vyšší krútiaci moment' },
      { text: '540E drží 540 ot/min pri nižších otáčkach motora → úspora paliva' },
      { text: '540E je elektrické prevedenie namiesto mechanického' },
      { text: '540E je novší bezpečnostný štandard' },
    ],
    correct: 1,
    explanation: 'PTO 540E (Economy) drží štandardných 540 ot/min, ale motor traktora beží na úsporných ~1500 ot/min namiesto plných 2100 ot/min. Úspora paliva 10–15 % pri ľahkých PTO úlohách (mulčovanie, kosenie). Nevhodné pre vysoké zaťaženie.',
    sourceUrl: '/slovnik/pto/',
    sourceLabel: 'PTO (Vývodový hriadeľ)',
  },
  {
    id: 'q7',
    question: 'Ktorá krajina je tradičným výrobcom značky Fendt?',
    options: [
      { text: 'Taliansko' },
      { text: 'Nemecko' },
      { text: 'Švédsko' },
      { text: 'Rakúsko' },
    ],
    correct: 1,
    explanation: 'Fendt je nemecký výrobca z bavorského Marktoberdorfu (založený v roku 1930 ako Xaver Fendt KG). Od roku 1997 je súčasťou amerického koncernu AGCO. Známy je CVT prevodovkou Vario, prémiovou kvalitou a charakteristickou zelenou farbou.',
    sourceUrl: '/znacky/fendt/',
    sourceLabel: 'Fendt',
  },
  {
    id: 'q8',
    question: 'Čo znamená skratka ISOBUS?',
    options: [
      { text: 'Medzinárodný systém ovládania palivového vstrekovania' },
      { text: 'Štandardizovaná komunikačná zbernica medzi traktorom a náradím (ISO 11783)' },
      { text: 'Taliansky systém na hodnotenie traktorov' },
      { text: 'Elektronická navigácia poľnohospodárskych dronov' },
    ],
    correct: 1,
    explanation: 'ISOBUS (ISO 11783) je medzinárodný štandard na komunikáciu medzi traktorom a náradím. Pred ISOBUS-om mal každý výrobca vlastný kábel/protokol. Dnes umožňuje ovládať sejačku Lemken z displeja traktora Fendt — jedno rozhranie, jedna kabeláž.',
    sourceUrl: '/slovnik/isobus/',
    sourceLabel: 'ISOBUS',
  },
  {
    id: 'q9',
    question: 'Akú presnosť má RTK GPS, ktorý sa používa v auto-steering systémoch?',
    options: [
      { text: '~1 meter' },
      { text: '~30 cm' },
      { text: '~2–3 cm' },
      { text: '~5 mm' },
    ],
    correct: 2,
    explanation: 'RTK (Real-Time Kinematic) GPS dosahuje presnosť 2–3 cm pomocou korekčného signálu z fixnej referenčnej stanice. Štandard pre auto-steering (autonómne riadenie), variable rate aplikácie a controlled traffic farming.',
    sourceUrl: '/slovnik/gps-rtk/',
    sourceLabel: 'RTK GPS',
  },
  {
    id: 'q10',
    question: 'Ktorá plodina zaberá na Slovensku najväčšiu výmeru ornej pôdy?',
    options: [
      { text: 'Kukurica na zrno' },
      { text: 'Pšenica ozimná' },
      { text: 'Repka ozimná' },
      { text: 'Jačmeň jarný' },
    ],
    correct: 1,
    explanation: 'Pšenica ozimná je dlhodobo najrozšírenejšou plodinou na slovenskej ornej pôde — pestuje sa jej viac než ktorejkoľvek inej obilniny. Nasleduje kukurica na zrno a repka ozimná.',
    sourceUrl: '/plodiny/psenice-ozima/',
    sourceLabel: 'Pšenica ozimná',
  },
  {
    id: 'q11',
    question: 'Čo je BISS v kontexte poľnohospodárskych dotácií?',
    options: [
      { text: 'Britský systém ekologického poľnohospodárstva' },
      { text: 'Základná podpora príjmu v rámci SPP (nahradila SAPS)' },
      { text: 'Certifikácia bezpečnosti poľnohospodárskej techniky' },
      { text: 'Bavorský poľnohospodársky štandard' },
    ],
    correct: 1,
    explanation: 'BISS (Basic Income Support for Sustainability) je hlavná priama platba Spoločnej poľnohospodárskej politiky. Vypláca sa na hektár spôsobilej plochy a nahradila predchádzajúcu jednotnú platbu na plochu (SAPS). Sadzba na hektár sa líši podľa členského štátu a roku.',
    sourceUrl: '/slovnik/biss/',
    sourceLabel: 'BISS',
  },
  {
    id: 'q12',
    question: 'Ktorá značka bola priekopníkom Quadtrac systému (gumené pásy namiesto kolies pri veľkých traktoroch)?',
    options: [
      { text: 'John Deere' },
      { text: 'Case IH' },
      { text: 'New Holland' },
      { text: 'Caterpillar' },
    ],
    correct: 1,
    explanation: 'Case IH uviedla Steiger Quadtrac s gumenými pásmi v roku 1996 — štyri nezávislé gumené pásy namiesto kolies. Znižuje tlak na pôdu, zlepšuje trakciu. Konkurenčné systémy: JD 9RX (od 2017), Challenger MT800 (od 1996).',
    sourceUrl: '/zebricky/traktory-nad-250-koni/',
    sourceLabel: 'Rebríček traktorov nad 250 koní',
  },
  {
    id: 'q13',
    question: 'Čo je LPIS?',
    options: [
      { text: 'Lokálna platforma pre investičné služby v poľnohospodárstve' },
      { text: 'Verejná evidencia poľnohospodárskej pôdy podľa dielov pôdnych blokov' },
      { text: 'Logistický systém na distribúciu palív' },
      { text: 'Letecký prieskum stavu úrody' },
    ],
    correct: 1,
    explanation: 'LPIS (Land Parcel Identification System) je evidencia spôsobilej poľnohospodárskej pôdy, ktorú vedie každý členský štát EÚ. Na diely pôdnych blokov sa viažu žiadosti o priame podpory — bez aktuálneho zákresu v LPIS ich nemožno podať. Na Slovensku priame podpory vypláca Pôdohospodárska platobná agentúra (PPA).',
    sourceUrl: '/slovnik/lpis/',
    sourceLabel: 'LPIS',
  },
  {
    id: 'q14',
    question: 'Ktorá krajina je tradičným výrobcom značky Kubota?',
    options: [
      { text: 'Čína' },
      { text: 'Kórea' },
      { text: 'Japonsko' },
      { text: 'India' },
    ],
    correct: 2,
    explanation: 'Kubota je japonský výrobca z Osaky (založená 1890). Dominantná v segmente kompaktných traktorov (20–100 koní) a komunálnej techniky. V Európe silno rastúca značka, najmä pre sady, vinice a komunálne použitie.',
    sourceUrl: '/znacky/kubota/',
    sourceLabel: 'Kubota',
  },
  {
    id: 'q15',
    question: 'Čo je Stage V v poľnohospodárstve?',
    options: [
      { text: 'Fáza rastu obilnín (5. vývojové štádium)' },
      { text: 'Najprísnejšia aktuálna emisná norma pre nesilničné dieselové motory (od 2020)' },
      { text: 'Piata generácia satelitných poľnohospodárskych dát' },
      { text: 'Stupeň zrelosti kompostu' },
    ],
    correct: 1,
    explanation: 'Stage V je najprísnejšia aktuálna emisná norma EÚ pre nesilničné dieselové motory (NRMM) — od januára 2020 povinná pre nové traktory. Vyžaduje DPF + SCR + filter na PM nanočastice. USA paralela: Tier 4 Final.',
    sourceUrl: '/slovnik/emisni-normy-stage/',
    sourceLabel: 'Emisné normy Stage / Tier',
  },
  {
    id: 'q16',
    question: 'Kto je najväčší výrobca poľnohospodárskej techniky na svete podľa obratu?',
    options: [
      { text: 'CNH Industrial (Case IH + New Holland)' },
      { text: 'AGCO (Fendt + Massey Ferguson + Valtra)' },
      { text: 'John Deere' },
      { text: 'CLAAS' },
    ],
    correct: 2,
    explanation: 'John Deere (Deere & Company) je dlhodobo najväčší výrobca poľnohospodárskej techniky — obrat viac ako 60 miliárd dolárov ročne, sídlo Moline, Illinois. CNH Industrial (Case + New Holland) je druhý ~30 mld $, AGCO tretí ~15 mld $.',
    sourceUrl: '/znacky/',
    sourceLabel: 'Prehľad značiek',
  },
];

/** Úrovně hodnocení; prahy (%) jsou shodné s cs, mění se jen texty. */
export const LEVELS_SK = [
  { min: 90, name: 'Legenda', description: 'Ste živá encyklopédia poľnohospodárskej techniky. Klobúk dole!', emoji: '🏆' },
  { min: 70, name: 'Expert', description: 'Skvelé! V hospodárstve aj technike sa vyznáte viac než väčšina.', emoji: '🎓' },
  { min: 50, name: 'Hospodár', description: 'Solídny výsledok — základy histórie a techniky máte v malíčku.', emoji: '👨‍🌾' },
  { min: 30, name: 'Učeň', description: 'Pár vecí už viete. Pozrite si encyklopédiu a slovník — uvidíte výrazné zlepšenie.', emoji: '📚' },
  { min: 0, name: 'Začiatočník', description: 'Žiadny strach — všetko sa dá naučiť. Začnite pri našich rebríčkoch a slovníku.', emoji: '🌱' },
];
