// Polská sada kvízu historie a technologií.
//
// 13 z 16 otázek je jazykově neutrálních (historie značek, technologie) → přeložené.
// 3 otázky byly vázané na ČESKOU jurisdikci (sazba VCS pro chmel v Kč, BISS v Kč,
// LPIS pod ÚKZÚZ/SZIF). Ty se NEPŘEKLÁDAJÍ — jsou nahrazené polskými ekvivalenty
// s reálnými sazbami ARiMR 2025 (zdroj: /doplaty-bezposrednie/, tytéž hodnoty jako
// tamní tabulka): PWD 488,55 zł/ha, pomidory 2097,56 zł/ha, chmiel 1864,49 zł/ha.
//
// Pořadí otázek i index správné odpovědi odpovídají cs — hodnocení a délka kvízu
// zůstávají stejné.
import type { QuizQuestion } from './kviz';

export const KVIZ_HISTORIE_PL: QuizQuestion[] = [
  {
    id: 'q1',
    question: `Która marka jako pierwsza wprowadziła bezstopniową CVT przekładnię do seryjnego traktora?`,
    options: [
      { text: `John Deere` },
      { text: `Fendt` },
      { text: `Massey Ferguson` },
      { text: `Case IH` },
    ],
    correct: 1,
    explanation: `Fendt wprowadził Vario CVT w roku 1995 w modelu Favorit 926 Vario. Stał się standardem premium traktorów — inni producenci dodali własne CVT (JD AutoPowr, NH Auto Command, Case CVX) dopiero po 2000.`,
    sourceUrl: '/slovnik/cvt-prevodovka/',
    sourceLabel: `CVT przekładnia`,
  },
  {
    id: 'q2',
    question: `W którym roku John Deere wyprodukował swój pierwszy stalowy pług?`,
    options: [
      { text: `1810` },
      { text: `1837` },
      { text: `1865` },
      { text: `1900` },
    ],
    correct: 1,
    explanation: `John Deere (kowal z Grand Detour, Illinois) skonstruował pierwszy stalowy pług w roku 1837. Ten pług potrafił obracać ciężką preriową glebę Środkowego Zachodu — dzięki temu Deere stał się fundamentem amerykańskiej rewolucji rolniczej.`,
    sourceUrl: '/znacky/john-deere/',
    sourceLabel: `John Deere`,
  },
  {
    id: 'q3',
    question: `Co to jest AdBlue?`,
    options: [
      { text: `Niebieski olej do malowania traktorów` },
      { text: `Płyn chłodzący do silników diesla` },
      { text: `32,5% wodny roztwór mocznika, który redukuje emisję NOx` },
      { text: `Dodatek przeciw zamarzaniu oleju napędowego` },
    ],
    correct: 2,
    explanation: `AdBlue to 32,5% wodny roztwór mocznika (chemicznie CO(NH₂)₂ + H₂O), który jest wtryskiwany do układu wydechowego silników diesla. W katalizatorze SCR reaguje z NOx → na nieszkodliwy azot i wodę. Standard od normy emisji Stage IV.`,
    sourceUrl: '/slovnik/adblue/',
    sourceLabel: `AdBlue`,
  },
  {
    id: 'q4',
    question: `Ile lat zajęło Zetorowi zbudowanie pierwszego miliona traktorów?`,
    options: [
      { text: `20 lat (1946–1966)` },
      { text: `40 lat (1946–1986)` },
      { text: `30 lat (1946–1976)` },
      { text: `50 lat (1946–1996)` },
    ],
    correct: 2,
    explanation: `Zetor wyprodukował milionowy traktor w roku 1976 — 30 lat od założenia (1946). W tym czasie Zetor był jednym z największych producentów traktorów w Europie i kluczowym eksporterem do krajów RWPG, Indii, Iraku i Etiopii.`,
    sourceUrl: '/znacky/zetor/',
    sourceLabel: `Zetor`,
  },
  {
    id: 'q5',
    question: `Która marka twierdzi, że wynalazła trzypunktowe hydrauliczne zawieszenie (Ferguson System)?`,
    options: [
      { text: `John Deere` },
      { text: `Massey Ferguson (pierwotnie Harry Ferguson)` },
      { text: `Fiat` },
      { text: `International Harvester` },
    ],
    correct: 1,
    explanation: `Harry Ferguson (północnoirlandzki konstruktor) opatentował Ferguson System w latach 30. XX wieku — trzypunktowe hydrauliczne zawieszenie z automatyczną regulacją obciążenia. W 1953 roku firma połączyła się z Massey-Harris → Massey-Ferguson. Trzypunkt jest do dziś standardem.`,
    sourceUrl: '/slovnik/tribod/',
    sourceLabel: `Trzypunktowe zawieszenie`,
  },
  {
    id: 'q6',
    question: `Jaki jest różnica między PTO 540 a 540E (Economy)?`,
    options: [
      { text: `540E ma wyższy moment obrotowy` },
      { text: `540E utrzymuje 540 obr/min przy niższych obrotach silnika → oszczędność paliwa` },
      { text: `540E jest wersją elektryczną zamiast mechaniczną` },
      { text: `540E jest nowszym standardem bezpieczeństwa` },
    ],
    correct: 1,
    explanation: `PTO 540E (Economy) utrzymuje standardowe 540 obr/min, ale silnik ciągnika pracuje na oszczędnych ~1500 obr/min zamiast pełnych 2100 obr/min. Oszczędność paliwa 10–15 % przy lekkich zadaniach PTO (mulczowanie, koszenie). Niewłaściwe do dużych obciążeń.`,
    sourceUrl: '/slovnik/pto/',
    sourceLabel: `PTO (Wał odbioru mocy)`,
  },
  {
    id: 'q7',
    question: `Który kraj jest tradycyjnym producentem marki Fendt?`,
    options: [
      { text: `Włochy` },
      { text: `Niemcy` },
      { text: `Szwecja` },
      { text: `Austria` },
    ],
    correct: 1,
    explanation: `Fendt jest niemieckim producentem z bawarskiego Marktoberdorfu (założony w 1930 roku jako Xaver Fendt KG). Od 1997 roku część amerykańskiego koncernu AGCO. Znany z przekładni CVT Vario, premium jakości i charakterystycznego zielonego koloru.`,
    sourceUrl: '/znacky/fendt/',
    sourceLabel: `Fendt`,
  },
  {
    id: 'q8',
    question: `Co oznacza skrót ISOBUS?`,
    options: [
      { text: `Międzynarodowy system sterowania wtryskiem paliwa` },
      { text: `Standaryzowana magistrala komunikacyjna między ciągnikiem a narzędziem (ISO 11783)` },
      { text: `Włoski system oceny ciągników` },
      { text: `Elektroniczna nawigacja dronów rolniczych` },
    ],
    correct: 1,
    explanation: `ISOBUS (ISO 11783) to międzynarodowy standard komunikacji między ciągnikiem a narzędziem. Przed ISOBUSem każdy producent miał własny kabel/protokół. Dziś umożliwia sterowanie siewnikiem Lemken z wyświetlacza ciągnika Fendt — jedno UI, jeden kabel.`,
    sourceUrl: '/slovnik/isobus/',
    sourceLabel: `ISOBUS`,
  },
  {
    id: 'q9',
    question: `Jaką dokładność ma RTK GPS, który jest używany w systemach auto-steering?`,
    options: [
      { text: `~1 metr` },
      { text: `~30 cm` },
      { text: `~2–3 cm` },
      { text: `~5 mm` },
    ],
    correct: 2,
    explanation: `RTK (Real-Time Kinematic) GPS osiąga dokładność 2–3 cm dzięki sygnałowi korekcyjnemu z stacji referencyjnej. Standard dla auto-steering (autonomiczne prowadzenie), aplikacji z zmienną dawką i controlled traffic farming.`,
    sourceUrl: '/slovnik/gps-rtk/',
    sourceLabel: `RTK GPS`,
  },
  {
    id: 'q10',
    question: `Która uprawa ma w Polsce najwyższą stawkę płatności związanej z produkcją (WPR 2025)?`,
    options: [
      { text: `Buraki cukrowe (~1284 zł/ha)` },
      { text: `Pomidory (~2098 zł/ha)` },
      { text: `Chmiel (~1864 zł/ha)` },
      { text: `Ziemniaki skrobiowe (~1581 zł/ha)` },
    ],
    correct: 1,
    explanation: `Najwyższą stawkę płatności związanej z produkcją mają pomidory — ok. 2098 zł/ha. Dalej chmiel (~1864 zł/ha), ziemniaki skrobiowe (~1581 zł/ha), truskawki (~1496 zł/ha) i buraki cukrowe (~1284 zł/ha). Stawki ustala ARiMR na podstawie koperty krajowej i powierzchni zgłoszonej we wnioskach.`,
    sourceUrl: '/doplaty-bezposrednie/',
    sourceLabel: `Dopłaty bezpośrednie 2025`,
  },
  {
    id: 'q11',
    question: `Co oznacza PWD w polskich dopłatach bezpośrednich?`,
    options: [
      { text: `Program Wsparcia Dochodowego dla sadowników` },
      { text: `Podstawowe wsparcie dochodów (~489 zł/ha)` },
      { text: `Państwowy Wykaz Działek rolnych` },
      { text: `Powiatowy Wskaźnik Dopłat` },
    ],
    correct: 1,
    explanation: `PWD (podstawowe wsparcie dochodów dla zrównoważoności) to główna płatność bezpośrednia WPR — ok. 489 zł/ha w 2025 r. do wszystkich kwalifikujących się hektarów. Odpowiednik unijnego BISS, który zastąpił wcześniejszy system JPO. Dla gospodarstwa 100 ha to ok. 48 900 zł rocznie, do tego dochodzi płatność redystrybucyjna (~177 zł/ha do pierwszych 30 ha).`,
    sourceUrl: '/doplaty-bezposrednie/',
    sourceLabel: `Dopłaty bezpośrednie 2025`,
  },
  {
    id: 'q12',
    question: `Która marka była pionierem systemu Quadtrac (gumowe gąsienice zamiast kół w dużych traktorach)?`,
    options: [
      { text: `John Deere` },
      { text: `Case IH` },
      { text: `New Holland` },
      { text: `Caterpillar` },
    ],
    correct: 1,
    explanation: `Case IH wprowadziła Steiger Quadtrac z gumowymi gąsienicami w 1996 roku — cztery niezależne gumowe gąsienice zamiast kół. Zmniejsza nacisk na glebę, poprawia przyczepność. Konkurencyjne systemy: JD 9RX (od 2017), Challenger MT800 (od 1996).`,
    sourceUrl: '/zebricky/traktory-nad-250-koni/',
    sourceLabel: `Ranking traktorów powyżej 250 KM`,
  },
  {
    id: 'q13',
    question: `Która instytucja prowadzi w Polsce system identyfikacji działek rolnych (LPIS) i wypłaca dopłaty?`,
    options: [
      { text: `KOWR (Krajowy Ośrodek Wsparcia Rolnictwa)` },
      { text: `ARiMR (Agencja Restrukturyzacji i Modernizacji Rolnictwa)` },
      { text: `GUS (Główny Urząd Statystyczny)` },
      { text: `PIORiN (Państwowa Inspekcja Ochrony Roślin)` },
    ],
    correct: 1,
    explanation: `ARiMR prowadzi LPIS (Land Parcel Identification System) — ewidencję kwalifikującej się powierzchni rolnej — i wypłaca płatności bezpośrednie. Wnioski składa się elektronicznie przez eWniosekPlus, a ARiMR kontroluje deklarowaną powierzchnię m.in. zdjęciami satelitarnymi (monitoring obszarowy).`,
    sourceUrl: '/doplaty-bezposrednie/',
    sourceLabel: `Dopłaty bezpośrednie 2025`,
  },
  {
    id: 'q14',
    question: `Który kraj jest tradycyjnym producentem marki Kubota?`,
    options: [
      { text: `Chiny` },
      { text: `Korea` },
      { text: `Japonia` },
      { text: `Indie` },
    ],
    correct: 2,
    explanation: `Kubota jest japońskim producentem z Osaki (założona w 1890 roku). Dominująca w segmencie kompaktowych traktorów (20–100 koni) i techniki komunalnej. W Europie silnie rosnąca marka, głównie dla sadów, winnic i zastosowań komunalnych.`,
    sourceUrl: '/znacky/kubota/',
    sourceLabel: `Kubota`,
  },
  {
    id: 'q15',
    question: `Co to jest Stage V w rolnictwie?`,
    options: [
      { text: `Faza wzrostu zbóż (5. stadium rozwoju)` },
      { text: `Najsurowsza aktualna norma emisji dla silników diesla poza drogami (od 2020)` },
      { text: `Piąta generacja satelitarnych danych rolniczych` },
      { text: `Stopień dojrzałości kompostu` },
    ],
    correct: 1,
    explanation: `Stage V to najsurowsza aktualna norma emisji UE dla silników diesla poza drogami (NRMM) — od stycznia 2020 roku obowiązkowa dla nowych traktorów. Wymaga DPF + SCR + filtra dla cząstek PM nano. USA paralela: Tier 4 Final.`,
    sourceUrl: '/slovnik/emisni-normy-stage/',
    sourceLabel: `Normy emisji Stage / Tier`,
  },
  {
    id: 'q16',
    question: `Kto jest największym producentem maszyn rolniczych na świecie według obrotów?`,
    options: [
      { text: `CNH Industrial (Case IH + New Holland)` },
      { text: `AGCO (Fendt + Massey Ferguson + Valtra)` },
      { text: `John Deere` },
      { text: `CLAAS` },
    ],
    correct: 2,
    explanation: `John Deere (Deere & Company) jest od dłuższego czasu największym producentem maszyn rolniczych — obrót przekraczający 60 miliardów dolarów rocznie, siedziba w Moline, Illinois. CNH Industrial (Case + New Holland) drugi ~30 mld $, AGCO trzeci ~15 mld $.`,
    sourceUrl: '/znacky/',
    sourceLabel: `Przegląd marek`,
  },
];
